zuul:
  routes:
    demo:
      path: /demo-filter
    user-service:
      path: /user/**
      serviceId: user-service
server:
  port: 8001
spring:
  application:
    name: zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka