server:
  port: 8001

mybatis:
  config-location: classpath:mybatis/mybatis.cfg.xml
  mapper-locations:
    - classpath:mapper/*.xml

spring:
  application:
    name: microservice-account
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://39.105.125.176:3306/spring_transaction?serverTimezone=UTC&useSSL=false
    username: root
    password: HH123
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
      test-while-idle: true
      validation-query: select 1

eureka:
  instance:
    prefer-ip-address: true
    instance-id: eureka8001.com
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/