server:
  port: 8884

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8881/eureka/

spring:
  application:
    name: ext-server
  datasource:
    url: jdbc:mysql://localhost:3306/cloud
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver

# MyBatis
mybatis:
  mapper-locations: classpath:mapper/**/*.xml
  type-aliases-package: com.example.ext_server.po
  configuration:
    map-underscore-to-camel-case: true