server:
  port: 8082
eureka:
  instance:
    prefer-ip-address: true
    instance-id: ${spring.cloud.client.ip-address}:${server.port}
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
spring:
  application:
    name: extension-microservice
  cloud:
    config:
      discovery:
        enabled: true
        service-id: CONFIG
      profile: test
  #数据库配置
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password:
    url: jdbc:mysql://localhost:3306/test?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT%2B8&useSSL=false
  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册
  jpa:
    show-sql: true
  http:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

