server:
  port: 8760

spring:
  application:
    name: zuul-server

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true



zuul:
  routes:
    country-provider:
      path: /country/**
      serviceID: country-server
    user-provider:
      path: /user/**
      serviceID: user-server
      stripPrdfix: false