server:
  port: 6001

spring:
  application:
    name: zuul

eureka:
  client:
    service-url:
      defaultZone: http://admin:admin@localhost:9001/eureka
  instance:
    instance-id: zuul6001
    prefer-ip-address: true

info:
  app.name: zuul

zuul:
  prefix: /mikeLv
  ignored-services: provider,consumer,orders
  routes:
    consumer: /c/**
    orders: /o/**
