spring:
  application:
    name: eureka
server:
  port: 8761
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: false # ???????????????Eureka Server?? ????true?? ????????????Eureka Server?? ?????? false??
    fetch-registry: false #???????Eureka Server???????????????true?? ??????????????? Eureka Server??????????????????????????????false??
    serviceUrl:
      defaultZone: http://localhost:8761/eureka #eureka.client.service-url.defaultZone ??????????Eureka Server ????????
  server:
    enable-self-preservation: false