server:
  port: 8040
spring:
  application:
    name: hand-manager-user
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot?useSSL=false
    password: 123456
    username: root



eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true


mybatis:
  configuration:
    map-underscore-to-camel-case: true