server:
  port: 8081
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_transaction?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    username: root
    password: root
  application:
    name: provider

mybatis:
  typeAliasesPackage: com.hand.providertest.Entity
  mapperLocations: classpath:mappers/*.xml
