server:
  port: 9002
spring:
  application:
    name: hand-info
  datasource:
    username: root
    password: password
    url: jdbc:mysql://127.0.0.1:3306/todo_service?useSSL=false&serverTimezone=Hongkong&characterEncoding=utf-8&autoReconnect=true
    type: com.zaxxer.hikari.HikariDataSource
mybatis:
  type-aliases-package: hand.pojo
logging:
  level:
    #    可以细分到每个包的日志级别
    hand: trace
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
  instance:
    prefer-ip-address: true
#      配置hystrix的全局超时允许时间
ribbon:
  ConnectTimeout: 1000 # ribbon链接超时时长
  ReadTimeout: 2000   # ribbon读取超时时长
  MaxAutoRetries: 0 # 当前服务重试次数
  MaxAutoRetriesNextServer: 0 # 切换服务重试次数
#ribbon是用来获取服务地址的，hystrix是用来控制在向服务发送请求后的响应的
feign:
  hystrix:
    enabled: true
#  下面是hystrix的配置
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 3000
      circuitBreaker:
        #        熔断阈值的大小，默认为20
        requestVolumeThreshold: 10
        #        过多长时间，熔断器再次检测是否开启，默认为5000，即5s钟
        sleepWindowInMilliseconds: 4000
        #        错误率，默认50%
        errorThresholdPercentage: 60