spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/springboot1?useSSL=false&serverTimezone=UTC&characterEncoding=utf-8
    username: zhang
    password: 123456
  application:
    name: spring-cloud-countryService

mybatis:
  type-aliases-package: com.zhang.countryprovider.pojo
  mapper-locations: mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 500
    default-statement-timeout: 80

server:
  port: 8004

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
