server:
  port: 8020
spring:
  application:
    name: country-service
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/clouddemo?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: 0097214214AB
    type: com.zaxxer.hikari.HikariDataSource
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
mybatis:
  mapper-locations: classpath:/mapper/*.xml
  type-aliases-package: com.hand.countryservice.domain
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
