server:
  port: 8080
netty:
  port: 8088
spring:
  application:
    name: hello
  datasource:
    username: root
    password: password
    url: jdbc:mysql://127.0.0.1:3306/mybatis_practice?useSSL=false&serverTimezone=Hongkong&characterEncoding=utf-8&autoReconnect=true
    type: com.zaxxer.hikari.HikariDataSource
#  rabbitmq:
#    host: 192.168.25.129
#  redis:
#    host: 192.168.25.129
mybatis:
  type-aliases-package: hand.pojo
logging:
  level:
    #    可以细分到每个包的日志级别
    wechat: trace
#      jwt工具类字段的配置
#jwt:
#  config:
#    key: jqh
#    ttl: 259200000