#配置mybatis
mybatis:
  mapper-locations: classpath:/com/hand/eureka/server/mapper/*Mapper.xml
  #设置别名
  type-aliases-package: com.hand.eureka.server.bean

#配置服务端口
server:
  port: 1001

#mysql驱动与
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/spring_cloud?useUnicode=true&characterEncoding=utf-8&useJDBCCompliantTimezoneShift=true&serverTimezone=UTC
    username: root
    password: root
  application:
    name: eureka-server-user

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:1000/eureka/

