spring:
  application:
    name: zuul
zuul:
  routes:
    user-extra-server:
      path: /country/**
      serviceId: user-extra-server
    user-server:
      path: /users/**
      serviceId: user-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
feign:
  hystrix:
    enabled: true
hystrix:
  command:
    default:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 1000
