spring:
  application:
    name: userManagerService
  activemq:
    broker-url:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/springcloud_demo?serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8&useSSL=false
    driver-class-name: com.mysql.jdbc.Driver
    type: com.alibaba.druid.pool.DruidDataSource
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
server:
  port: 8081

eureka:
  client:
    serviceUrl:
      defaultZone=http://localhost:8761/eureka/:
mybatis:
  mapper-locations: classpath:mapper/*.xml #注意：一定要对应mapper映射xml文件的所在路径
  type-aliases-package: huanglehao.study.usermanagerservice.entity # 注意：对应实体类的路径
