server:
  port: 8080
spring:
  application:
    name: hand-gateway-zuul
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true
logging:
  level:
    com.netflix: debug
zuul:
  routes:
    hand-manager-user: /user/**
    hand-user-detail: /userdetail/**
