spring:
  application:
    name: springcloud-zuul-gateway
server:
  port: 6001


#eureka
eureka:
  client:
    service-url:
      defaultZone: http://localhost:7001/eureka
  instance:
    instance-id: myzuul.com
    prefer-ip-address: true

#zuul
zuul:
  ignore-service: "*"
  routes:
    product.serviceId: EUREKA-CLINT-USER
    product.path: /product/**
