server:
  port: 8100
spring:
  application:
    name: Zuul-gateway
eureka:
  instance:
    instance-id: Zuul-gateway:${server.port}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://localhost:8000/eureka/
zuul:
  routes:
    area-server:
      path: /area/**
      serviceId: area-service
    user-server:
      path: /user/**
      serviceId: user-service
